// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH5EU60eipJhdejG-roUdMu-GMPUnxAZ4',
    appId: '1:1081999367489:web:d9f9e091445988c827d5c0',
    messagingSenderId: '1081999367489',
    projectId: 'recipe-genui',
    authDomain: 'recipe-genui.firebaseapp.com',
    storageBucket: 'recipe-genui.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXGV52Qx16yJuWAb0HoXCjjg8lt3A4D9k',
    appId: '1:1081999367489:android:cf476248b16c522d27d5c0',
    messagingSenderId: '1081999367489',
    projectId: 'recipe-genui',
    storageBucket: 'recipe-genui.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCvfrV_egy6QhkOA2rR1wtCok8StcDLBQ',
    appId: '1:1081999367489:ios:26f2561df8e279c627d5c0',
    messagingSenderId: '1081999367489',
    projectId: 'recipe-genui',
    storageBucket: 'recipe-genui.firebasestorage.app',
    iosBundleId: 'com.example.recipeGenui',
  );
}
